services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/main/server/app          # live reload — reflects local file changes
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - FLASK_DEBUG=1